import type { ElevationSample, LatLng, ManeuverStep, Waypoint } from '../types';
import { formatDistance, formatDuration } from './fuel';

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Build a GPX 1.1 document with waypoints + route track. */
export function buildGpxDocument(options: {
  name: string;
  waypoints: Waypoint[];
  track: LatLng[];
  steps?: ManeuverStep[];
}): string {
  const { name, waypoints, track, steps = [] } = options;
  const wptXml = waypoints
    .map(
      (wp) => `  <wpt lat="${wp.lat}" lon="${wp.lng}">
    <name>${escapeXml(wp.label)}</name>
    <type>${escapeXml(wp.stopType)}</type>
  </wpt>`,
    )
    .join('\n');

  const trkpts = track
    .map((p) => `      <trkpt lat="${p.lat}" lon="${p.lng}"></trkpt>`)
    .join('\n');

  const rtepts = steps
    .map(
      (step) => `  <rtept lat="${step.location.lat}" lon="${step.location.lng}">
    <name>${escapeXml(step.instruction)}</name>
    <desc>${escapeXml(step.streetName || step.type)}</desc>
  </rtept>`,
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Wayfare" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(name)}</name>
    <desc>Wayfare road trip export</desc>
  </metadata>
${wptXml}
  <rte>
    <name>${escapeXml(name)} — turns</name>
${rtepts}
  </rte>
  <trk>
    <name>${escapeXml(name)}</name>
    <trkseg>
${trkpts}
    </trkseg>
  </trk>
</gpx>
`;
}

/** Plain-text roadbook for download / print. */
export function buildRoadbookText(options: {
  title: string;
  waypoints: Waypoint[];
  steps: ManeuverStep[];
  totalDistanceKm: number;
  totalDurationMinutes: number;
}): string {
  const {
    title,
    waypoints,
    steps,
    totalDistanceKm,
    totalDurationMinutes,
  } = options;

  const lines: string[] = [
    title,
    '='.repeat(title.length),
    '',
    `Total: ${formatDistance(totalDistanceKm)} · ${formatDuration(totalDurationMinutes)}`,
    '',
    'Stops',
    '-----',
    ...waypoints.map(
      (wp, index) =>
        `${index + 1}. ${wp.label} (${wp.stopType}) — ${wp.lat.toFixed(5)}, ${wp.lng.toFixed(5)}`,
    ),
    '',
    'Turn-by-turn',
    '------------',
  ];

  if (steps.length === 0) {
    lines.push('No maneuver steps available for this route.');
  } else {
    for (const step of steps) {
      const dist =
        step.distanceMeters >= 1000
          ? `${(step.distanceMeters / 1000).toFixed(1)} km`
          : `${Math.round(step.distanceMeters)} m`;
      lines.push(
        `${step.index + 1}. ${step.instruction} (${dist})`,
      );
    }
  }

  lines.push('', 'Generated by Wayfare', '');
  return lines.join('\n');
}

export function downloadTextFile(
  filename: string,
  contents: string,
  mime = 'text/plain;charset=utf-8',
): void {
  const blob = new Blob([contents], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function elevationSamplesToSparkline(
  samples: ElevationSample[],
): string {
  return samples.map((s) => s.elevationMeters.toFixed(0)).join(',');
}
